version: '3.7'
services: 
    frontend:
        container_name: frontend
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start
        
        ports:
            - "4001:3000"        
        volumes: 
            - ./:/frontend
            - /frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
